package zph.zhjx.com.chat.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import zph.zhjx.com.chat.dao.People;
import zph.zhjx.com.chat.dao.User;

import zph.zhjx.com.chat.db.PeopleDao;
import zph.zhjx.com.chat.db.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig peopleDaoConfig;
    private final DaoConfig userDaoConfig;

    private final PeopleDao peopleDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        peopleDaoConfig = daoConfigMap.get(PeopleDao.class).clone();
        peopleDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        peopleDao = new PeopleDao(peopleDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(People.class, peopleDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        peopleDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public PeopleDao getPeopleDao() {
        return peopleDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
